---
# https://access.redhat.com/articles/3626371#bgenerating-an-access-tokenb-4
- name: Generating an access token
  uri:
    url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    method: POST
    body_format: form-urlencoded
    return_content: true
    body:
      grant_type: "refresh_token"
      client_id: "rhsm-api"
      refresh_token: "{{ rh_offline_token }}"
  register: temp_token

# - name: show temp_token only
#   debug:
#     var: temp_token.json.access_token

- name: retrieving SHA for AAP download
  uri:
    url: https://api.access.redhat.com/management/v1/images/cset/{{ app_image }}
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ temp_token.json.access_token }}"
    method: GET
    body_format: form-urlencoded
    return_content: true
  register: sha_value

# - name: display SHA checksum
#   debug:
#     var: sha_value

- name: display SHA checksum
  debug:
    var: sha_value.json.body[1].checksum

- name: retrieving download link via sha_value
  uri:
    url: https://api.access.redhat.com/management/v1/images/{{ sha_value.json.body[1].checksum }}/download
    headers:
      accept: "application/json"
      Authorization: "Bearer {{ temp_token.json.access_token }}"
    method: GET
  register: download_url
  failed_when: "'bundle' not in sha_value.json.body[1].filename"

- name: show download URL
  debug:
    var: download_url.url

- name: Download aap.tar.gz
  get_url:
    url: "{{ download_url.url }}"
    dest: "{{ aap_setup_dir }}/aap.tar.gz"
    checksum: "sha256: {{ sha_value.json.body[1].checksum }}"
