---
- name: Fail if component not selected
  ansible.builtin.fail:
    msg: Invalid aap_component value. Valid values are 'tower' and 'automationhub'
  when: aap_component is undefined

- name: Fail if unknown component
  ansible.builtin.fail:
    msg: Invalid aap_component value. Valid values are 'tower' and 'automationhub'
  when:
    - aap_component != 'tower'
    - aap_component != 'automationhub'

- name: Include vars
  ansible.builtin.include_vars:
    file: "vars/{{ aap_component }}.yml"

- name: set package pattern fact
  ansible.builtin.set_fact:
    aap_setup_pkg_pattern: "{{ __aap_setup_pkg_pattern }}"
  when: aap_setup_pkg_pattern is undefined

- name: set installed package fact
  ansible.builtin.set_fact:
    aap_installed_package: "{{ __aap_installed_package }}"
  when: aap_installed_package is undefined

- name: Ensure Ansible is installed
  ansible.builtin.package:
    name: ansible
    state: present

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Ensure setup dir is created
  ansible.builtin.file:
    path: "{{ aap_setup_dir }}"
    state: directory
    mode: 0750
    owner: root
    group: root

- name: Unzip the latest Ansible Automation Platform software
  ansible.builtin.unarchive:
    src: "{{ aap_setup_package_url }}"
    dest: "{{ aap_setup_dir }}"
    remote_src: yes
  when: aap_installed_package not in ansible_facts.packages

- name: Find installer absolute path
  ansible.builtin.find:
    paths: "{{ aap_setup_dir }}"
    patterns: "{{ aap_setup_pkg_pattern }}"
    file_type: directory
    recurse: false
  register: aap_setup_find

- name: Set install directory fact
  ansible.builtin.set_fact:
    aap_setup_dir_full: "{{ aap_setup_find.files[0].path }}"

- name: Set install script facts
  ansible.builtin.set_fact:
    aap_setup_script: "{{ aap_setup_dir_full }}/setup.sh"
    aap_inventory_path: "{{ aap_setup_dir_full }}/inventory"

- name: Create Automation Platform inventory file
  ansible.builtin.template:
    src: aap-inventory.j2
    dest: "{{ aap_inventory_path }}"
    owner: root
    group: root
    mode: 0600
    backup: true

- name: Run Automation Platform installer
  ansible.builtin.shell:
    cmd: "{{ aap_setup_script }} -i {{ aap_inventory_path }}"
    chdir: "{{ aap_setup_dir_full }}"
  when: aap_installed_package not in ansible_facts.packages
